"""remove credit_score

Revision ID: e26183e3c645
Revises: fa52194cc87a
Create Date: 2024-01-08 22:58:26.211948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26183e3c645'
down_revision = 'fa52194cc87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('credit_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_score', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
